//! Issue #1066 (Phase 2 of #1064): run every clud-launched Bash tool call
//! under `set -u`.
//!
//! `set -u` (nounset) aborts the shell on any unset-variable expansion, which
//! kills the incident class #1064 was filed about at its source: `rm -rf "$SP"/`
//! with an unset `$SP` expands to `rm -rf /` today, and dies with a visible
//! `SP: unbound variable` under nounset — before argv is ever built.
//!
//! It also covers the one thing neither the `block_bad_cmd` hook nor the `tap`
//! gate can reach. **Redirections are performed by the shell, not the wrapped
//! program**: `tap cmd > "$VAR/out"` truncates whatever the shell resolves, and
//! no amount of argv inspection sees it. DD-056 records that as the residual
//! risk and names `set -u` as the proportionate mitigation.
//!
//! # Why `BASH_ENV`, and the evidence it is actually in effect
//!
//! #1066 asked for the mechanism to be verified rather than assumed — "a
//! mechanism that silently does nothing is worse than not shipping it, because
//! it reads as coverage that is not there." Measured inside a live Claude Code
//! Bash tool call:
//!
//! ```text
//! $ case $- in *i*) echo interactive;; *) echo non-interactive;; esac
//! non-interactive
//! $ echo "flags: $-"
//! flags: hmtBc
//! ```
//!
//! No `i`, so the tool-call shell is non-interactive and **does** read
//! `BASH_ENV`. Confirmed end to end on the same shell:
//!
//! ```text
//! $ BASH_ENV=/tmp/x/env.sh bash -c 'echo "[${NOPE}]"'   # env.sh holds `set -u`
//! bash: line 1: NOPE: unbound variable
//! $ bash -c 'echo "[${NOPE}]"'
//! []
//! ```
//!
//! The tool-call shell is also a direct child of the harness process, so it
//! inherits the session environment this module contributes to.
//!
//! # Chaining rather than clobbering
//!
//! A user who already has `BASH_ENV` set is not overridden into silence: the
//! generated file sources their previous value after enabling nounset. Skipping
//! our injection when theirs is present would be the silent-gap failure the
//! issue warns about; clobbering it would break their setup. Chaining is the
//! only option that does neither.

use std::path::{Path, PathBuf};

/// The variable a non-interactive bash reads a startup file from.
pub const BASH_ENV_KEY: &str = "BASH_ENV";

/// Where the inherited `BASH_ENV` is stashed so the generated file can source
/// it. Read only by that file.
pub const PREV_KEY: &str = "CLUD_PREV_BASH_ENV";

/// Escape hatch. Set to `1`/`true`/`yes`/`on` to launch without nounset.
///
/// Env-only and deliberately not repo-configurable, matching the
/// `CLUD_HOOK_DISPATCH` precedent: a repo should not be able to switch off a
/// safety default for whoever runs an agent in it.
pub const OPT_OUT_KEY: &str = "CLUD_NO_BASH_NOUNSET";

/// File name under the clud state dir.
const FILE_NAME: &str = "bash-nounset.sh";

/// Whether the caller asked to launch without nounset.
pub fn is_opted_out() -> bool {
    matches!(std::env::var(OPT_OUT_KEY), Ok(v) if is_truthy(&v))
}

fn is_truthy(raw: &str) -> bool {
    matches!(
        raw.trim().to_ascii_lowercase().as_str(),
        "1" | "true" | "yes" | "on"
    )
}

/// The startup file's contents.
///
/// Order is load-bearing: the user's own `BASH_ENV` is sourced *before*
/// nounset is armed. Their file was written for a stock shell, and stock
/// startup files routinely test unset variables — `[ -z "$PS1" ]`,
/// `$SSH_AUTH_SOCK` — so arming first would abort every tool call with an
/// error pointing at their file, for a policy they did not ask for. Ours goes
/// last, which also means a `set +u` in their file cannot leave us disarmed.
///
/// `${CLUD_PREV_BASH_ENV:-}` keeps the `:-` form even though nounset is not
/// active on that line yet: it costs nothing, and it stays correct if the
/// user's file (or a future edit) turns nounset on above it. The readability
/// test keeps a stale path from failing every tool call.
pub fn script_body() -> String {
    format!(
        "# Generated by clud (#1066). Sourced by every non-interactive bash\n\
         # via BASH_ENV. Do not edit; it is rewritten at launch.\n\
         if [ -n \"${{{PREV_KEY}:-}}\" ] && [ -r \"${{{PREV_KEY}}}\" ]; then\n\
         \x20   . \"${{{PREV_KEY}}}\"\n\
         fi\n\
         set -u\n"
    )
}

/// Write the startup file under `state_dir` and return its path.
///
/// The contents are fixed, so the common case is that the file is already
/// correct and this touches nothing. That is not just an optimisation: a plain
/// `fs::write` truncates first, and concurrent clud launches share this path,
/// so a second launch could hand a bash that is mid-source an empty file. That
/// shell comes up silently unarmed — the "reads as coverage that is not there"
/// failure #1066 names. Writing only when the content differs removes the
/// window for every launch after the first; the rename makes the write itself
/// atomic, so even the first one is never observed half-written.
fn ensure_script(state_dir: &Path) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(state_dir)?;
    let path = state_dir.join(FILE_NAME);
    let body = script_body();
    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == body) {
        return Ok(path);
    }
    // Unique per process, so two concurrent launches cannot collide on the
    // staging name and rename each other's partial file into place.
    let staging = state_dir.join(format!("{FILE_NAME}.{}.tmp", std::process::id()));
    std::fs::write(&staging, &body)?;
    match std::fs::rename(&staging, &path) {
        Ok(()) => Ok(path),
        Err(err) => {
            let _ = std::fs::remove_file(&staging);
            Err(err)
        }
    }
}

/// The `(key, value)` overrides to layer onto a backend child environment.
///
/// Empty when opted out, and empty when the file cannot be written — a shell
/// pointed at a missing `BASH_ENV` is not an error, so a failure here would be
/// invisible rather than loud, and silently-absent coverage is worse than
/// none.
pub fn env_overrides() -> Vec<(String, String)> {
    let Some(state_dir) = state_dir() else {
        return Vec::new();
    };
    env_overrides_at(&state_dir, is_opted_out(), std::env::var(BASH_ENV_KEY).ok())
}

/// `<state-dir>`, honoring `CLUD_DAEMON_STATE_DIR` exactly as
/// `gc::delete_audit::audit_log_path` and `daemon::paths::default_state_dir`
/// do. `None` when no home resolves, which makes the whole policy a no-op
/// rather than guessing at a path.
fn state_dir() -> Option<PathBuf> {
    match std::env::var(crate::daemon::ENV_STATE_DIR) {
        Ok(v) if !v.is_empty() => Some(PathBuf::from(v)),
        _ => dirs::home_dir().map(|home| home.join(".clud").join("state")),
    }
}

/// Test seam — state dir, opt-out, and any inherited `BASH_ENV` are passed in
/// so the policy is exercisable without mutating the process environment.
pub fn env_overrides_at(
    state_dir: &Path,
    opted_out: bool,
    inherited: Option<String>,
) -> Vec<(String, String)> {
    if opted_out {
        return Vec::new();
    }
    let Ok(path) = ensure_script(state_dir) else {
        return Vec::new();
    };
    let mut overrides = vec![(BASH_ENV_KEY.to_string(), path.display().to_string())];
    // Only chain a value that is not already ours, so relaunching inside a
    // clud session cannot build a self-sourcing loop.
    if let Some(prev) = inherited.filter(|value| !value.is_empty() && Path::new(value) != path) {
        overrides.push((PREV_KEY.to_string(), prev));
    }
    overrides
}

#[cfg(test)]
#[path = "nounset_tests.rs"]
mod tests;
