"""Project initialization utilities for clud."""

from pathlib import Path


def project_init(example: str | None = None, outputdir: Path | None = None) -> None:
    """Initialize a new project."""
    # For now, this is a placeholder implementation
    output_path = outputdir or Path.cwd()

    if example:
        print(f"Initializing project with example: {example}")
    else:
        print("Initializing basic project")

    print(f"Output directory: {output_path}")

    # Create basic project structure
    if not output_path.exists():
        output_path.mkdir(parents=True, exist_ok=True)

    # Create a simple README
    readme_path = output_path / "README.md"
    if not readme_path.exists():
        readme_path.write_text("# New Project\n\nGenerated by clud\n")

    print("Project initialized successfully")
