name: Linux ARM Integration Test
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call:
    uses: ./.github/workflows/_integration-test.yml
    with:
      runs-on: ubuntu-24.04-arm
      artifact-name: wheels-linux-arm
