name: macOS ARM Preflight
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call:
    uses: ./.github/workflows/_preflight.yml
    with:
      runs-on: macos-15
      artifact-name: wheels-macos-arm
