name: macOS x86 Integration Test
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call:
    uses: ./.github/workflows/_integration-test.yml
    with:
      runs-on: macos-15-intel
      artifact-name: wheels-macos-x86
