name: macOS ARM Unit Test
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call:
    uses: ./.github/workflows/_unit-test.yml
    with:
      runs-on: macos-15
