name: Windows x86 Preflight
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  call:
    uses: ./.github/workflows/_preflight.yml
    with:
      runs-on: windows-2025
      artifact-name: wheels-windows-x86
